### ISSUE TITLE
Fix reference handling 

### ISSUE THREAD

**Issue by Xazax-hun** [mgehre/clang#15]
The following code will warn on the assignment:
```
my_pointer global_pointer;
void f(my_pointer &p) { // expected-note {{it was never initialized here}}
  // p is a out-parameter, so its pset is {invalid}
  (void)*p;           // expected-warning {{dereferencing a dangling pointer}}
  p = global_pointer; // OK, *this is not validated on assignment operator call
                      // TODO-remove expected-warning@-1 {{dereferencing a dangling pointer}}
}
```

This code will, however work as intended, if the LHS of the assignment is a value and not a reference. The source of the problem is that each time we see a reference, the calculated PSet for the expression will be the pointee of the reference. If we se a value, the calculated PSet will point to the value (and not the pointee of the value).
This was done in order to make the following code snippet work:
 ```
  int i, j;
  int &ref1 = i;
  __lifetime_pset_ref(ref1); // expected-warning {{pset(ref1) = (i)}}

  int *p = &ref1;
  __lifetime_pset(p); // expected-warning {{pset(p) = (i)}}
```

We want the `pset(p)` to be `i` rather than `ref1`.

So what should we do to make both of these work?

**Comment by mgehre** [comment]
I would guess that `p = global_pointer;` calls the (default) assignment operator on `my_pointer`, and there we check that `*this` is valid. By automatically annoatating `*this` as [[gsl::out]] for assignment operators, the diagnostic should be suppressed.

**Comment by Xazax-hun** [comment]
Unfortunately, this is not the case. We already handle *this as out for assignments.
Here is a testcase to showcase that: https://github.com/mgehre/clang/commit/8ef9e3d91c3952ef4580b38306291db059e2ab67

The problem is specific to references.

**Comment by mgehre** [comment]
I already get 
```
void f(my_pointer &p) {
  // p is a out-parameter, so its pset is {invalid}
  __lifetime_pset_ref(p); //  dereferencing a dangling pointer, pset(p) = ((unknown))
````
Do we initialize the refersTo set of p correctly? p has type `my_pointer &`, and should point to deref_p.
deref_p has type `my_pointer` and has pset (invalid).

**Comment by Xazax-hun** [comment]
Maybe we should postpone the investigation of this until https://github.com/mgehre/clang/issues/22 is fixed? That might make reason about this problem and experimenting with it easier.

**Comment by Xazax-hun** [comment]
Also I wonder if it is unknown because we set to unknown during VisitDeclrefExpr

**Comment by mgehre** [comment]
I think this is closed with the recent commits
