### ISSUE TITLE
Use source ranges whenever possible

### ISSUE THREAD

**Issue by Xazax-hun** [mgehre/clang#20]
Having a source location to pinpoint the problem is useful but it could also be ambiguous in some cases. We should try to provide source ranges whenever it is possible.

**Comment by mgehre** [comment]
What is left to be done here?

**Comment by Xazax-hun** [comment]
We actually never emit warnings with ranges at the moment. If we would like to have the code snippet underlined, we might need to change that. But otherwise, we have everything.

**Comment by mgehre** [comment]
I thought I saw underlined diagnostics in compiler explorer?

Gábor Horváth <notifications@github.com> schrieb am Sa., 22. Sep. 2018,
21:16:

**Comment by Xazax-hun** [comment]
I think those might have been from other warnings. But now, our warnings will also provide underlined diagnostics. Fixed in https://github.com/mgehre/clang/commit/5bd87fb8497635ed0d377ebcf0c0f2ccff9b57e7 :)
