### ISSUE TITLE
Support for deref_ locations for parameters

### ISSUE THREAD

**Issue by Xazax-hun** [mgehre/clang#22]
Now the pset of a pointer param should be the deref of that param:
```
void f(int *p) {
  // pset(p) == deref_p
}
```

Maybe we could use the same Order, so Order for owners mean prime, Order for Pointer means deref?

**Comment by Xazax-hun** [comment]
Some diferences between Pointer and Owner "Orders":
When o is invalidated, we need to invalidate o', o'' etc.
When p is invalidated we do not need to invalidate *p, **p etc.

What about merging?
Right now when we have o' and o'', we will chose o''.
What if we have *p and **p. Do we want to choose one over the other?
Can we have different deref levels of the same object in the PSet at all? We would need casting to make that happen. Should we just ban this and continue with unknown pset if casts were involved?

**Comment by mgehre** [comment]
I think the deref_location needs to be a proper `Variable`, because we need to store it's pset so we can check it on function exit.

**Comment by Xazax-hun** [comment]
Ok, I think adding support to Variable is the way to go, but it is not as easy as just adding an integer to represent the DerefLevel.

Consider the following cases:
```
void f(Struct **p) {
  (*(*p)).field;
  (*p)->field;
  *(*(*p)).ptr_field;
}
```

The point is, we have a list of fields and derefs might appear in arbitrary locations during the field chain. This also complicates the `getType` method of `Variable`.

We could have a vector where each entry can be a field or a dereference, so:
  `(*(*p)).field;`
could have `p` as its base and `*,*,field` would be the elements in the vector.

What do you think?

**Comment by mgehre** [comment]
Let's look at the cases we have to handle.
We add deref locations only for parameters.
Struct S
{
int *q;
int **pp;
};
f(int **p, S* sp, S s)

We need to add
int * deref_p;
int* deref_sp_q;
int** deref_sp_pp;
int* s_q;
int** s_pp;
int* s_deref_pp;


Did I capture all cases? So we have zero or one deref and zero or one field
in two possible orderings.

The vector approach would capture that, and even a bit more in case we
later want to expand more levels of fields/derefs. Agreed!

Gábor Horváth <notifications@github.com> schrieb am Do., 6. Sep. 2018,
23:04:

**Comment by Xazax-hun** [comment]
Great! Do you want to work on it or should I do this?
