### ISSUE TITLE
Too eager validation of references

### ISSUE THREAD

**Issue by Xazax-hun** [mgehre/clang#28]
The following code will trigger a warning:
```
void f(char &c) {
	c = 1; // warning: dereferencing a dangling pointer [-Wlifetime]
}
```

The reason is, we want to validate the pointee of references early, whenever we see a DeclRefExpr. I think this behavior is wrong.
We should only validate the pointee of references:
* when we create them
* when we pass them to functions
* are there more cases?

**Comment by mgehre** [comment]
If think here we just did not initalize the pset of `c` correctly (to point to deref_c). I remember that in the `PopulatePSetForParams`, references are excluded with comment `But references
    // already handled as they are pointing to the deref loc.` and I always wondered where that would happen. Seems that we should really add psets of references in `PopulatePSetForParams` (because they are inputs)?

**Comment by Xazax-hun** [comment]
The problem is, currently references are special. Every time we see a reference, we will work with the PSet of the pointee rather than the pset of the reference itself. It is not special to `PopulatePSetForParams`. This is what `VisitDeclRefExpr` and other code in `PSetBuilder` does.

**Comment by Xazax-hun** [comment]
This is closely related to https://github.com/mgehre/clang/issues/15

**Comment by Xazax-hun** [comment]
Ok, I think I will give this a try, to set a proper deref locations for references.

**Comment by Xazax-hun** [comment]
You were right setting a proper deref location for references did help a bit. The problem is, the error messages are a bit confusing now, we emit derefs even for reference types. But this might be OK for now.

**Comment by mgehre** [comment]
Actually I'm currently doing work in PopulatePSetForParams due fix a crash
I saw from creduce. If you don't mind, I will do this in the same go.

Gábor Horváth <notifications@github.com> schrieb am Do., 13. Sep. 2018 um
20:50 Uhr:

**Comment by Xazax-hun** [comment]
Sorry, I went ahead and commited a fix in the meantime. But feel free to change it to your liking as long as we do not regress :)
