### ISSUE TITLE
Handle CXXDeleteExpr?

### ISSUE THREAD

**Issue by Xazax-hun** [mgehre/clang#32]
Probably we want to warn for the following code:
```
void delete_expr(gsl::not_null<int *> p) {
  delete p;
  *p = 2;
}
```
Is this mentioned in the paper at all?

**Comment by mgehre** [comment]
I would say it's sane to set the pset(p) = {invalid} (and warn if pset(p) already was invalid) in this case, but it's also worthwhile to mention this as an issue in the other repo.

**Comment by Xazax-hun** [comment]
I think the MSVC implementation also set the PSet to invalid.
But rather than setting the pointer pointing to invalid, it might be better to actually invalidate the pointee.
So code like this:
```
p = q;
delete q;
*p = 2;
```
would also warn.

**Comment by mgehre** [comment]
Good catch!

**Comment by Xazax-hun** [comment]
Should be done in https://github.com/mgehre/clang/commits/lifetime
