### ISSUE TITLE
False positive with lifetime-extended temporary

### ISSUE THREAD

**Issue by jspam** [mgehre/clang#36]
The following code

```cpp
#include <vector>

int main() {
    const auto& myVector = std::vector<int> { 1, 2, 3, 4 };
#if 0
    return myVector.front();
#else
    return *myVector.cbegin();
#endif
}
```

generates a warning which seems to be unjustified:
```
$ /mnt/xdata/hdd/llvm-build-500/bin/clang++ -std=c++17 -Wlifetime -Wlifetime-debug test1.cpp 
test1.cpp:8:13: warning: passing a dangling pointer as argument [-Wlifetime]
    return *myVector.cbegin();
            ^
test1.cpp:4:59: note: temporary was destroyed at the end of the full expression
    const auto& myVector = std::vector<int> { 1, 2, 3, 4 };
                                                          ^
1 warning generated.
```

It seems to me that the temporary `std::vector` is not destroyed at the end of line 4 because a `const auto&` reference is bound to it. However, I'm not a C++ guru, so if I got this wrong, shame on me :)

Note also that this does not happen when calling `myVector.front()` instead.

llvm: `d8e175bca5919de13fe003cab6b10f23af3d055d`
clang: `99451dc6bfb8fcf48a371fb390f9d9f7e19be779`

**Comment by mgehre** [comment]
Interesting, thank you for reporting it. 
You are right, `myVector` lifetime-extends the temporary owner, and the iterator returned from `cbegin` points into that owner. Seems that we wrongly invalidate the iterator to earlier (maybe because at that point we ignore the lifetime-extension).
We will work on a fix.

**Comment by Xazax-hun** [comment]
Sorry for the delay, this should be fixed in https://github.com/mgehre/clang/commit/759b4e1099d5dc9394a8b9b7212e033309362fec
