### ISSUE TITLE
Unhandled VAArgExpr

### ISSUE THREAD

**Issue by cen1** [mgehre/clang#38]
I am having fun with `-Wlifetime` on various projects and got a core dump on one. It does not happen without `-Wlifetime` so I assume it has something to do with it.

[crash.log](https://github.com/mgehre/clang/files/2583112/crash.log)
[asnprintf-2e0d9a.cpp.log](https://github.com/mgehre/clang/files/2583117/asnprintf-2e0d9a.cpp.log)
[asnprintf-2e0d9a.sh.log](https://github.com/mgehre/clang/files/2583118/asnprintf-2e0d9a.sh.log)

**Comment by mgehre** [comment]
Thank you for taking the time to report this crash. It's a development assert that points out that we have not implemented support for the `VAArgExpr` of clang's AST yet.

**Comment by Xazax-hun** [comment]
Sorry for the delay, the assertion failure should be now suppressed in https://github.com/mgehre/clang/commit/1944b8e062f58e0099399ec3d2a495a7cede8266

Note that, we do not plan to support VAArgs in the near future, so the analysis will simply not reason about those values resulting from VAArgs.

**Comment by cen1** [comment]
Thanks, I'll give it a try.
