### ISSUE TITLE
Complier crash when using Boost spirit

### ISSUE THREAD

**Issue by roccomoretti** [mgehre/clang#40]
The following file results in a compiler crash when using `-Wlifetime` (but not when omitting the option), at least when using Boost 1.53 or 1.55.

    #include <boost/spirit/include/classic_core.hpp>
    #include <boost/spirit/include/classic_closure.hpp>
    
    class Tag {};
    
    using namespace boost::spirit::classic; // Removing this `using` avoids the crash.
    
    struct tag_closure : public boost::spirit::classic::closure< tag_closure, Tag >
    {};
    
    struct tag_grammar : public boost::spirit::classic::grammar<tag_grammar,tag_closure::context_t> {
        tag_grammar() {}
    }; // tag_grammar

[Full preprocessed source](https://github.com/mgehre/clang/files/2654331/Tag_pp.cpp.txt) and [error output](https://github.com/mgehre/clang/files/2654334/Tag_crash.txt) are attached.

`llvm: d8e175bca5919de13fe003cab6b10f23af3d055d`
`clang: 4385bf94e655affaf1555bfbde3ccbb5c16c3ee8`

**Comment by Xazax-hun** [comment]
Looks like this is a problem with automatic categorization. The clang community does not like the idea of automatically categorizing types. The upstream version will only check explicitly annotated types, thus will not have this crash. A separate tool will suggest annotations as fixits. It is unlikely we will ever fix this problem with the current version.  We try to upstream changes as quickly as possible to get you unblocked.
